// Code generated by Google Gemini

document.addEventListener("DOMContentLoaded", () => {
  const slideshowImage = document.getElementById("slideshow-image");
  const slideshowText = document.getElementById("slideshow-text");
  const backgroundAudio = document.getElementById("background-audio");

  // IMPORTANT: Populate these arrays with your actual image paths, texts, and sound paths
  // Images should be in the 'images/' folder, sounds in the 'sounds/' folder.
  const images = [
    "images/animal_1.png",
    "images/animal_2.png",
    "images/animal_3.png",
    "images/animal_4.png",
    "images/animal_5.png",
    "images/animal_6.png",
    "images/animal_7.png",
    "images/animal_8.png",
    "images/animal_9.png",
    "images/animal_10.png",
    "images/animal_11.png",
    "images/animal_12.png",
    "images/animal_13.png",
    "images/animal_14.png",
    "images/animal_15.png",
    "images/animal_16.png",
    "images/animal_17.png",
    "images/animal_18.png",
    "images/animal_19.png",
    "images/animal_20.png",
    "images/animal_21.png",
    "images/animal_22.png",
    "images/animal_23.png",
    "images/animal_24.png",
    "images/animal_25.png",
    "images/animal_26.png",
    "images/animal_27.png",
    "images/animal_28.png",
    "images/animal_29.png",
    "images/animal_30.png",
    "images/animal_31.png",
    "images/animal_32.png",
    "images/animal_33.png",
    "images/animal_34.png",
    "images/animal_35.png",
    // Add more image paths here
  ];

  const texts = [
    "Zha'ra tu'li ve'ka, shra'ni kar'ra k'li",
    "Kra'li'ta no'ka, vri'ka t'ala'ri",
    "Sha'ra tu'li, kri'ka ve'ka, la'ra ni'li.",
    "Thra'li shra'ka, ve'ka ni'li, kar'ra no'ka",
    "Zha'ri ve'ka, shra'li kri'ka, tu'li ra'ka",
    "Kra'li'ta ve'ka, shra'ni'li, kri'ka no'ka",
    "Sha'ra ve'ka, kri'li'ta, tu'li shra'ka",
    "Thra'li kri'ka, ve'ka no'ka, la'ra ve'li",
    "Zha'ra kri'li, shra'ni ve'ka, tu'li kri'ka",
    "Kra'li'ta shra'ka, ve'ka kri'li, la'ra ni'li",
    "Nul'ka shan'ra, kri'la ve'thul, mar'liak",
    "Thal'ra veth, s'kaal nith, ul'ra sha'lin",
    "Zha'ra ve'ka, shra'li kri'ka, la'ra ni'li",
    "Kra'li'ta kri'ka, ve'ka no'ka, shra'ni ve'li",
    "Sha'ra kri'li, ve'ka no'ka, shra'ni kri'ka",
    "Thra'li ve'ka, kri'li'ta, tu'li ra'ka",
    // Add more text strings here
  ];

  const sounds = [
    "sounds/sound1.wav",
    "sounds/sound2.wav",
    "sounds/sound3.wav",
    "sounds/sound4.wav",
    // Add more sound paths here
  ];

  let currentImageIndex = -1;
  let currentTextIndex = -1;
  let currentSoundIndex = -1;

  // Configuration for slideshow intervals
  const imageChangeInterval = 3000; // 3 seconds
  const textChangeInterval = 5000; // 5 seconds
  const soundChangeInterval = 15000; // 15 seconds

  function getRandomIndex(array, currentIndex) {
    let newIndex;
    do {
      newIndex = Math.floor(Math.random() * array.length);
    } while (newIndex === currentIndex);
    return newIndex;
  }

  function changeImage() {
    if (images.length === 0) return;
    slideshowImage.classList.remove("active");
    setTimeout(() => {
      currentImageIndex = getRandomIndex(images, currentImageIndex);
      slideshowImage.src = images[currentImageIndex];
      slideshowImage.classList.add("active");
    }, 1000); // Wait for fade-out transition
  }

  function changeText() {
    if (texts.length === 0) return;
    slideshowText.classList.remove("active");
    setTimeout(() => {
      currentTextIndex = getRandomIndex(texts, currentTextIndex);
      slideshowText.textContent = texts[currentTextIndex];
      slideshowText.classList.add("active");
    }, 1000); // Wait for fade-out transition
  }

  function playRandomSound() {
    if (sounds.length === 0) return;
    currentSoundIndex = getRandomIndex(sounds, currentSoundIndex);
    backgroundAudio.src = sounds[currentSoundIndex];
    backgroundAudio.volume = 0.5; // Adjust volume as needed
    backgroundAudio.play().catch((e) => console.log("Audio play failed:", e));
  }

  // Initial calls
  changeImage();
  changeText();
  playRandomSound();

  // Set intervals for changes
  setInterval(changeImage, imageChangeInterval);
  setInterval(changeText, textChangeInterval);
  setInterval(playRandomSound, soundChangeInterval);
});
